### ISSUE TITLE
New Questions

### ISSUE THREAD

**Issue by poing** [kaykyb/freelancer-hosted-projects#1]
Can't drag **new** questions.  The default placement, hides the title block of the element.
![Screenshot_2019-06-10 Invite](https://user-images.githubusercontent.com/11417007/59167368-dbfc0900-8b6b-11e9-9759-d894fc9e89f7.png)

Seems I can also drag items outside the work area **without** any way to recover.  Can the canvas be scrollable or resized?

![Screenshot_2019-06-10 Invite(1)](https://user-images.githubusercontent.com/11417007/59167440-3ac18280-8b6c-11e9-9d49-9f1b8e368a08.png)

**Comment by kaykyb** [comment]
The canvas is draggable, just click and drag the background. I'll fix the new questions' positions.

![gif-canvas](https://user-images.githubusercontent.com/15058641/59168065-99561480-8b0a-11e9-8b23-acd614fcbe87.gif)

**Comment by poing** [comment]
> The canvas is draggable, just click and drag the background. I'll fix the new questions' positions.

Thanks!  That does help, *I kept trying to scroll.*

**Comment by kaykyb** [comment]
The issue was fixed. Now, new questions are positioned at least 96px below the border of the canvas.

Also added a "button" to help users that may have the same problem with the dragging/scrolling of the canvas.

![invite-fab](https://user-images.githubusercontent.com/15058641/59169681-a4607300-8b11-11e9-802b-cfba1593d629.jpg)

The dragging mechanism is still the same, the button just help users that may not see the different cursor on the background of the canvas.
